### ISSUE TITLE
Asking for a new feature: force minimum lending value

### ISSUE THREAD

**Issue by Shoananas** [dutu/poloLender#106] opened 2017-07-14 13:59 UTC
Hello,

We have the POLOLENDER_MINRATE config vars that works very well.
Currently, the bot simply waits for the following to be true before lending :
`[current lending value proposed by poloniex-advisor] >= POLOLENDER_MINRATE`

 I would like to suggest a new feature like this:
```
If ([current lending value proposed by poloniex-advisor] < POLOLENDER_MINRATE) {
    use POLOLENDER_MINRATE
}
```

I don't want to lend with a rate < 0.035 because, well, i feel like it's not worth it, people always use the whole 48hours when they take a loan with such a low rate and we can't take advantage of mini-spike (let's say 0.05, it sucks but it's still a good increase) after.

Recently, I saw the lending rates at around 0.03%, i stopped the bot and put a manual offer at 0.05, my offer was taken some hours later and I did the right move seeing the average lending time when the rates are very low.

What do you think about this feature?

Thank you for your hard work as always!

Regards,

**Comment by abclution** [comment] 2017-07-15 08:53
Newest version seems to have this feature.
Please try it. 👍

**Comment by dutu** [comment] 2017-07-17 08:11
Let me know if I understand you correctly:

* currently: no lending offer is posted when the lending-advisor-rate is below POLOLENDER_MINRATE
* your proposal is that instead of no offer, poloLender Pro should post an offer at POLOLENDER_MINRATE

Is my understanding right?

**Comment by Shoananas** [comment] 2017-07-17 08:12
Yes

**Comment by dutu** [comment] 2017-07-18 12:38
added in v1.1.0

**Comment by Shoananas** [comment] 2017-07-18 14:24
nice, thank you!

**Comment by Shoananas** [comment] 2017-07-20 09:45
Hi,

I hope I'm doing right to use this issue instead of creating another one.

I don't think the feature is working as intended. It keeps offering/cancelling.
There is probably a step somewhere in your code that checks if the opened offers are different from the optimized offer of pololender-advisor.

See the logs:

> Loan offered  #522580672 BTC     0.52707197 at 0.050000%, duration 2 days 
> OfferCanceled #522580672 BTC     0.52707197 at 0.050000%, brr 0.042451% 
> Loan offered  #522580762 BTC     0.52707197 at 0.050000%, duration 2 days 
> OfferCanceled #522580762 BTC     0.52707197 at 0.050000%, brr 0.042451% 
> Loan offered  #522580835 BTC     0.52707197 at 0.050000%, duration 2 days 
> OfferCanceled #522580835 BTC     0.52707197 at 0.050000%, brr 0.042451% 
> Loan offered  #522580938 BTC     0.52707197 at 0.050000%, duration 2 days 
> OfferCanceled #522580938 BTC     0.52707197 at 0.050000%, brr 0.042451% 
> Loan offered  #522581060 BTC     0.52707197 at 0.050000%, duration 2 days 
> OfferCanceled #522581060 BTC     0.52707197 at 0.050000%, brr 0.042699% 
> Loan offered  #522581107 BTC     0.52707197 at 0.050000%, duration 2 days 
> OfferCanceled #522581107 BTC     0.52707197 at 0.050000%, brr 0.042699% 
> Loan offered  #522581187 BTC     0.52707197 at 0.050000%, duration 2 days 
> Loan offered  #522581266 BTC     0.52707197 at 0.050000%, duration 2 days 
> OfferCanceled #522581266 BTC     0.52707197 at 0.050000%, brr 0.042299% 
> Loan offered  #522581369 BTC     0.52707197 at 0.050000%, duration 2 days 
> OfferCanceled #522581369 BTC     0.52707197 at 0.050000%, brr 0.042299% 
> Loan offered  #522581444 BTC     0.52707197 at 0.050000%, duration 2 days 
> OfferCanceled #522581444 BTC     0.52707197 at 0.050000%, brr 0.042299% 
> Loan offered  #522581500 BTC     0.52707197 at 0.050000%, duration 2 days 
> OfferCanceled #522581500 BTC     0.52707197 at 0.050000%, brr 0.042299% 
> Loan offered  #522581613 BTC     0.52707197 at 0.050000%, duration 2 days

**Comment by dutu** [comment] 2017-07-25 22:24
fixed in release 1.2.0. If you can pls let me know if it's working as intended

**Comment by Shoananas** [comment] 2017-07-26 17:42
I still have the same issue

**Comment by dutu** [comment] 2017-07-26 18:03
Have you upgraded to 1.2.0? I have tested it with no issue. Do you have a log?

**Comment by dutu** [comment] 2017-07-26 18:48
@Shoananas , sorry, there was a floating-point arithmetic issue which initially didn't appear in my testing. It has been fixed now.

**Comment by Shoananas** [comment] 2017-07-26 20:53
looks like it's working now =) thank you

**Closed as completed** 2017-07-27 07:04 UTC
Labels: enhancement
